repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.275"
    hooks:
      - id: ruff
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python3.10
        args:
          - "--line-length=100"
  - repo: local
    hooks:
      - id: pytest
        name: Pytest and Coverage
        description: 100% unit testing coverage for Python code.
        entry: pytest -s -v tests --capture=sys --cov=scorecard_app --cov-report term-missing
        language: system
        pass_filenames: false
        always_run: true
        types: [python]
